from django.urls import path
from apps.scrapers import views, views_admin

urlpatterns = [
    # ── Workspace do superadmin ──
    path("painel-admin/", views_admin.superadmin_usuarios, name="superadmin-usuarios"),
    path("painel-admin/criar/", views_admin.superadmin_criar_usuario, name="superadmin-criar-usuario"),
    path("painel-admin/saude/", views_admin.superadmin_saude, name="superadmin-saude"),
    path("painel-admin/saude.json", views_admin.superadmin_saude_json, name="superadmin-saude-json"),
    path("painel-admin/saude/<int:incidente_id>/retestar/", views_admin.superadmin_saude_retest, name="superadmin-saude-retestar"),
    path("painel-admin/infra/", views_admin.superadmin_infra, name="superadmin-infra"),
    path("painel-admin/usuario/<int:user_id>/", views_admin.superadmin_usuario_detalhe, name="superadmin-usuario"),
    path("painel-admin/usuario/<int:user_id>/suspender/", views_admin.superadmin_suspender, name="superadmin-suspender"),
    path("painel-admin/usuario/<int:user_id>/cotas/", views_admin.superadmin_cotas, name="superadmin-cotas"),
    path("painel-admin/usuario/<int:user_id>/impersonar/", views_admin.superadmin_impersonar, name="superadmin-impersonar"),
    path("painel-admin/parar-impersonar/", views_admin.superadmin_parar_impersonar, name="superadmin-parar-impersonar"),

    path("", views.dashboard, name="scraper-dashboard"),
    path("comecar/", views.comecar, name="scraper-comecar"),
    path("conta/", views.configurar_conta, name="scraper-conta"),
    path("run/", views.run_scraper_stream, name="scraper-run"),
    path("gerar-links/", views.gerar_links_stream, name="scraper-gerar-links"),
    path("ofertas/", views.scrape_ofertas_stream, name="scraper-ofertas-run"),
    path("cupons-codigo/", views.scrape_cupons_codigo_stream, name="scraper-cupons-codigo"),
    path("buscar-termo/", views.buscar_termo_stream, name="scraper-buscar-termo"),
    path("automacao/", views.automacao_control, name="scraper-automacao"),
    path("ml/", views.ml_conexao_painel, name="scraper-ml-conexao"),
    path("ml/status/", views.ml_conexao_status_json, name="scraper-ml-status"),
    path("ml/start/", views.ml_conexao_start, name="scraper-ml-start"),
    path("ml/salvar/", views.ml_conexao_salvar, name="scraper-ml-salvar"),
    path("ml/cancelar/", views.ml_conexao_cancelar, name="scraper-ml-cancelar"),
    path("ml/frames/", views.ml_conexao_frames, name="scraper-ml-frames"),
    path("ml/input/", views.ml_conexao_input, name="scraper-ml-input"),
    path("ml-relatorio/", views.ml_relatorio_conexao_painel, name="scraper-ml-relatorio-conexao"),
    path("ml-relatorio/status/", views.ml_relatorio_conexao_status_json, name="scraper-ml-relatorio-status"),
    path("ml-relatorio/start/", views.ml_relatorio_conexao_start, name="scraper-ml-relatorio-start"),
    path("ml-relatorio/salvar/", views.ml_relatorio_conexao_salvar, name="scraper-ml-relatorio-salvar"),
    path("ml-relatorio/cancelar/", views.ml_relatorio_conexao_cancelar, name="scraper-ml-relatorio-cancelar"),
    path("ml-relatorio/frames/", views.ml_relatorio_conexao_frames, name="scraper-ml-relatorio-frames"),
    path("ml-relatorio/input/", views.ml_relatorio_conexao_input, name="scraper-ml-relatorio-input"),
    path("amazon/", views.amazon_conexao_painel, name="scraper-amazon-conexao"),
    path("amazon/status/", views.amazon_conexao_status_json, name="scraper-amazon-status"),
    path("amazon/start/", views.amazon_conexao_start, name="scraper-amazon-start"),
    path("amazon/salvar/", views.amazon_conexao_salvar, name="scraper-amazon-salvar"),
    path("amazon/cancelar/", views.amazon_conexao_cancelar, name="scraper-amazon-cancelar"),
    path("amazon/frames/", views.amazon_conexao_frames, name="scraper-amazon-frames"),
    path("amazon/input/", views.amazon_conexao_input, name="scraper-amazon-input"),
    path("top/", views.top_promocoes, name="scraper-top"),
    path("r/<str:token>/", views.redirect_rastreado, name="scraper-redirect"),
    path("sincronizar-receitas/", views.sincronizar_receitas, name="scraper-sincronizar-receitas"),
    path("enviar-produto/", views.enviar_produto_stream, name="scraper-enviar-produto"),
    path("buscar-promocoes/", views.buscar_promocoes_stream, name="scraper-buscar-promocoes"),
    path("config/", views.configuracoes, name="scraper-configuracoes"),
    path("enviar-agora/", views.enviar_agora_stream, name="scraper-enviar-agora"),
    path("whatsapp/", views.whatsapp_painel, name="scraper-whatsapp"),
    path("whatsapp/status/", views.whatsapp_status_json, name="scraper-whatsapp-status"),
    path("whatsapp/qr.png", views.whatsapp_qr_png, name="scraper-whatsapp-qr"),
    path("whatsapp/refresh-grupos/", views.whatsapp_refresh_grupos, name="scraper-whatsapp-refresh"),
    path("whatsapp/grupos/", views.whatsapp_grupos_json, name="scraper-whatsapp-grupos"),
    path("whatsapp/desconectar/", views.whatsapp_desconectar, name="scraper-whatsapp-desconectar"),
    path("telegram/", views.telegram_painel, name="scraper-telegram"),
    path("telegram/status/", views.telegram_status_json, name="scraper-telegram-status"),
    path("telegram/conectar/", views.telegram_conectar, name="scraper-telegram-conectar"),
    path("telegram/desconectar/", views.telegram_desconectar, name="scraper-telegram-desconectar"),
]
