"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env vive na raiz do projeto (Spreading/), um nível acima de django/
load_dotenv(BASE_DIR.parent / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Vem do .env em produção. Fallback inseguro só serve para DEBUG/dev local.
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY") or "django-insecure-dev-only-CHANGE-ME-in-.env"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "1") == "1"

if not DEBUG and SECRET_KEY.startswith("django-insecure"):
    raise RuntimeError("Defina DJANGO_SECRET_KEY no .env antes de rodar com DEBUG=0.")

# Hosts liberados (CSV no .env). Em dev cai no localhost.
# Default cobre Fly.io (.fly.dev) e túnel do cloudflare (.trycloudflare.com).
ALLOWED_HOSTS = [h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", ".fly.dev,.trycloudflare.com").split(",") if h.strip()]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", ".fly.dev", ".trycloudflare.com"]
elif DEBUG:
    ALLOWED_HOSTS += ["localhost", "127.0.0.1"]
# Fly injeta o hostname do app; libera automaticamente sem precisar configurar.
_fly_app = os.getenv("FLY_APP_NAME", "")
if _fly_app:
    ALLOWED_HOSTS.append(f"{_fly_app}.fly.dev")

# Origens confiáveis para CSRF (precisa de esquema: https://app.seudominio.com).
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv(
    "DJANGO_CSRF_TRUSTED_ORIGINS", "https://*.fly.dev,https://*.trycloudflare.com").split(",") if o.strip()]
if _fly_app:
    CSRF_TRUSTED_ORIGINS.append(f"https://{_fly_app}.fly.dev")


# Application definition

INSTALLED_APPS = [
    'apps.scrapers',
    'apps.accounts',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serve os static (admin/etc) direto do processo, sem CDN/nginx.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.SecurityHeadersMiddleware',
    # Tranca usuário logado mas com e-mail não verificado (multi-tenant SaaS).
    'apps.accounts.middleware.EmailVerificadoMiddleware',
]

# CSP em modo report-only começa desligado. Para testar sem quebrar nada:
# DJANGO_CSP_REPORT_ONLY=1 no .env -> navegador só reporta, não bloqueia.
CSP_REPORT_ONLY = os.getenv("DJANGO_CSP_REPORT_ONLY", "0") == "1"

# Tranca TODO o site por padrão (inclusive em DEBUG). Views públicas marcam
# @login_not_required (login/signup/reset/verificação). Anônimo cai no login.
MIDDLEWARE.insert(
    MIDDLEWARE.index('django.contrib.auth.middleware.AuthenticationMiddleware') + 1,
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
)

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'apps' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Prod: DATABASE_URL (Postgres) — ex: postgres://user:pass@host:5432/db
# Sem DATABASE_URL cai no SQLite. Em prod (Fly) o SQLite fica no volume /data
# (se montado) para sobreviver a deploys; em dev fica ao lado do projeto.
_sqlite_dir = Path("/data") if Path("/data").is_dir() else BASE_DIR
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': _sqlite_dir / 'db.sqlite3',
    }
}
_database_url = os.getenv("DATABASE_URL", "")
if _database_url:
    import dj_database_url
    DATABASES['default'] = dj_database_url.parse(_database_url, conn_max_age=600, ssl_require=False)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# collectstatic joga tudo aqui no build do container; WhiteNoise serve com hash + gzip.
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}


# ─────────────────────────────────────────────────────────────
# WhatsApp sender (serviço Node em node.js/index.js)
# ─────────────────────────────────────────────────────────────
WHATSAPP_API_URL = os.getenv("WHATSAPP_API_URL", "http://localhost:3000")
# Reutiliza a API_KEY do .env (mesma chave do serviço Node).
WHATSAPP_API_KEY = os.getenv("WHATSAPP_API_KEY") or os.getenv("API_KEY", "")
# Grupo de destino padrão (id no formato 12345@g.us). Pegue via GET /api/grupos.
WHATSAPP_GRUPO_ID = os.getenv("WHATSAPP_GRUPO_ID", "")


# ─────────────────────────────────────────────────────────────
# Telegram sender (Bot API). Cada usuário conecta o próprio bot pela web
# (Conexão Telegram -> token salvo no Perfil). Este valor é só o FALLBACK global
# usado quando o usuário não tem token próprio (single-tenant/compat).
# ─────────────────────────────────────────────────────────────
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")


# ─────────────────────────────────────────────────────────────
# Afiliado — tag/ID que DEVE aparecer no link final (verificação A3).
# Sem ela, o link não gera comissão. Pegue inspecionando um link real do
# Link Builder (param matt_word/matt_tool/tracking_id na URL de destino).
# ─────────────────────────────────────────────────────────────
AFILIADO_TAG = os.getenv("AFILIADO_TAG", "")
# Recusar envio quando o link não carrega a tag? (1=recusa, 0=envia c/ aviso)
AFILIADO_EXIGIR = os.getenv("AFILIADO_EXIGIR", "1") == "1"


# ─────────────────────────────────────────────────────────────
# Amazon — Associates (BR) + Creators API (sucessor da PA-API 5.0, desligada
# em 2026-05-15). Auth OAuth2: Credential ID/Secret -> token bearer (~1h).
# Pegue as credenciais em Associates Central > Tools > Creators API.
# AMAZON_PARTNER_TAG: sua tag de afiliado (ex 'meusite-20') — vai no ?tag= do link.
# ─────────────────────────────────────────────────────────────
AMAZON_PARTNER_TAG = os.getenv("AMAZON_PARTNER_TAG", "")
AMAZON_CREATOR_CREDENTIAL_ID = os.getenv("AMAZON_CREATOR_CREDENTIAL_ID", "")
AMAZON_CREATOR_CREDENTIAL_SECRET = os.getenv("AMAZON_CREATOR_CREDENTIAL_SECRET", "")
# Host do endpoint da Creators API (sem https://). Confirmar na doc autenticada.
AMAZON_CREATORS_HOST = os.getenv("AMAZON_CREATORS_HOST", "")
# Host do marketplace BR usado para montar o link canônico /dp/{ASIN}.
AMAZON_MARKETPLACE = os.getenv("AMAZON_MARKETPLACE", "www.amazon.com.br")
# Desconto mínimo (%) para um item entrar no feed de ofertas Amazon.
AMAZON_MIN_SAVINGS_PCT = float(os.getenv("AMAZON_MIN_SAVINGS_PCT", "15"))
# Palavras-chave de categorias amplas que alimentam o "feed" de ofertas Amazon
# (a Creators API não expõe um feed de ofertas; varremos buscas com min savings).
AMAZON_FEED_KEYWORDS = [
    k.strip() for k in os.getenv(
        "AMAZON_FEED_KEYWORDS",
        "echo dot,fone bluetooth,smart tv,notebook,air fryer,smartwatch,"
        "aspirador robo,monitor,ssd,cafeteira,perfume,tenis",
    ).split(",") if k.strip()
]


# ─────────────────────────────────────────────────────────────
# LLM local (Ollama) — descrições engraçadas das ofertas
# ─────────────────────────────────────────────────────────────
LLM_ATIVO = os.getenv("LLM_ATIVO", "1") == "1"
OLLAMA_URL = os.getenv("OLLAMA_URL", "http://localhost:11434")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama3.2:3b")


# ─────────────────────────────────────────────────────────────
# Redis (Celery broker/backend + cache). Em prod: um REDIS_URL só (ex: Upstash
# no Fly). CELERY_BROKER_URL/RESULT_BACKEND ainda sobrescrevem se você quiser
# separar. Em dev sem Redis, cai em localhost (Celery) e cache local (abaixo).
# ─────────────────────────────────────────────────────────────
REDIS_URL = os.getenv("REDIS_URL", "")
_redis_default = REDIS_URL or "redis://localhost:6379/0"
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", _redis_default)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", _redis_default)
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True


# ─────────────────────────────────────────────────────────────
# Cache — compartilhado entre workers do gunicorn.
# A conexão web do ML guarda o estado (fase, live_view_url) no cache: a thread
# que segura o browser remoto vive em UM worker, mas o polling do front pode cair
# em outro. Com o cache local (por processo) isso não enxergaria o estado, então
# usamos o mesmo Redis do Celery em prod. Em dev sem Redis, cai no cache local.
# ─────────────────────────────────────────────────────────────
_REDIS_CACHE_URL = os.getenv("REDIS_CACHE_URL") or os.getenv("REDIS_URL") or (
    CELERY_BROKER_URL if os.getenv("USE_REDIS_CACHE", "0") == "1" else ""
)
if _REDIS_CACHE_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": _REDIS_CACHE_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "spreading-local",
        }
    }


# ─────────────────────────────────────────────────────────────
# Autenticação — rotas de redirect
# ─────────────────────────────────────────────────────────────
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "login"

# PBKDF2 (default do Django, ~1M iterações) é seguro. Se argon2-cffi estiver
# instalado, usa Argon2 (mais resistente a GPU). Só prepende se importável —
# evita quebrar login/signup quando a lib não está instalada.
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
]
try:
    import argon2  # noqa: F401
    PASSWORD_HASHERS.insert(0, "django.contrib.auth.hashers.Argon2PasswordHasher")
except ImportError:
    pass


# ─────────────────────────────────────────────────────────────
# Cookies de sessão / CSRF
# ─────────────────────────────────────────────────────────────
SESSION_COOKIE_HTTPONLY = True          # JS não lê o cookie de sessão
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14  # 14 dias
SESSION_SAVE_EVERY_REQUEST = True       # renova expiração a cada request (sliding)


# ─────────────────────────────────────────────────────────────
# Hardening — ligado só fora do DEBUG (produção atrás de HTTPS)
# ─────────────────────────────────────────────────────────────
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Atrás de proxy/load balancer que termina TLS:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 365  # 1 ano
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# E-mail — em dev imprime no console; em prod (ou EMAIL_FORCE_SMTP=1) usa SMTP.
# Titan (HostGator): EMAIL_HOST=smtp.titan.email, EMAIL_PORT=465, EMAIL_USE_SSL=1
# (alternativa: porta 587 com EMAIL_USE_TLS=1). SSL e TLS são mutuamente exclusivos.
EMAIL_FORCE_SMTP = os.getenv("EMAIL_FORCE_SMTP", "0") == "1"
if DEBUG and not EMAIL_FORCE_SMTP:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.titan.email")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "465"))
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
    EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "1") == "1"
    # TLS só quando SSL desligado (porta 587). Django proíbe os dois juntos.
    EMAIL_USE_TLS = (not EMAIL_USE_SSL) and os.getenv("EMAIL_USE_TLS", "0") == "1"
    DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "no-reply@spreading.app")

# Cooldown (horas) entre alertas repetidos de conexão caída p/ não floodar e-mail.
ALERTA_CONEXAO_COOLDOWN_H = int(os.getenv("ALERTA_CONEXAO_COOLDOWN_H", "6"))
# Dias sem atualizar o auth.json do ML antes de considerar a sessão "stale" (caída).
ML_AUTH_STALE_DIAS = int(os.getenv("ML_AUTH_STALE_DIAS", "7"))

# Onde as sessões do ML (auth_{id}.json) são gravadas. Precisa ser PERSISTENTE:
# no Fly o filesystem da imagem é efêmero (some a cada deploy). Default: volume
# /data se existir (produção), senão a pasta do scraper (dev). Override: ML_AUTH_DIR.
_ml_auth_default = "/data/ml_sessions" if Path("/data").is_dir() else str(
    BASE_DIR / "apps" / "scrapers" / "scraper_mercadolivre")
ML_AUTH_DIR = os.getenv("ML_AUTH_DIR", _ml_auth_default)
os.makedirs(ML_AUTH_DIR, exist_ok=True)

# --- Browser hospedado (Browserbase) p/ login web do Mercado Livre ---
# O servidor é headless; o login do ML acontece num Chromium remoto transmitido
# pro navegador do usuário (live view). Sem essas chaves, a tela avisa o usuário.
BROWSERBASE_API_KEY = os.getenv("BROWSERBASE_API_KEY", "")
BROWSERBASE_PROJECT_ID = os.getenv("BROWSERBASE_PROJECT_ID", "")
# País do proxy residencial (reduz bloqueio anti-bot do ML no login).
BROWSERBASE_PROXY_COUNTRY = os.getenv("BROWSERBASE_PROXY_COUNTRY", "BR")
