# Generated by Django 6.0.5 on 2026-05-13 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campanha_id', models.CharField(max_length=100, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('tipo_desconto', models.CharField(max_length=20)),
                ('valor_desconto', models.FloatField()),
                ('link_original', models.URLField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco_sem_desconto', models.FloatField()),
                ('preco_com_cupom', models.FloatField()),
                ('link_produto', models.URLField()),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('cupom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='scrapers.cupom')),
            ],
        ),
    ]
