# Generated by Django 6.0.5 on 2026-05-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='campanha_id',
            field=models.CharField(db_index=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
