# Generated by Django 6.0.5 on 2026-05-13 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0002_produto_campanha_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='cupom',
        ),
    ]
