# Generated by Django 6.0.5 on 2026-05-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0003_remove_produto_cupom'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='macro_categoria',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
