# Generated by Django 6.0.5 on 2026-05-21 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0005_add_cupom_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapers.produto')),
            ],
        ),
    ]
