# Generated by Django 6.0.5 on 2026-05-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0006_historicoenvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='valor_minimo',
            field=models.FloatField(default=0.0),
        ),
    ]
