# Generated by Django 6.0.5 on 2026-06-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0008_produto_link_afiliado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macro_categoria', models.CharField(max_length=100)),
                ('grupo_id', models.CharField(max_length=100)),
                ('grupo_nome', models.CharField(blank=True, default='', max_length=255)),
                ('intervalo_minutos', models.PositiveIntegerField(default=60)),
                ('min_desconto_percent', models.FloatField(default=15.0)),
                ('horas_cooldown', models.PositiveIntegerField(default=24)),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_envio', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
