# Generated by Django 6.0.5 on 2026-06-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0009_configuracaoenvio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupomCodigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_desconto', models.CharField(default='porcentagem', max_length=20)),
                ('valor_desconto', models.FloatField(default=0.0)),
                ('valor_minimo', models.FloatField(default=0.0)),
                ('validade', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='origem',
            field=models.CharField(db_index=True, default='cupom', max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='campanha_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
