# Generated by Django 6.0.5 on 2026-06-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0010_cupomcodigo_produto_origem_alter_produto_campanha_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='frete_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
