# Generated by Django 6.0.5 on 2026-06-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0011_produto_frete_full_produto_imagem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoenvio',
            name='termo_busca',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='configuracaoenvio',
            name='macro_categoria',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
