# Generated by Django 6.0.5 on 2026-06-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0012_configuracaoenvio_termo_busca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_checkout',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
