# Generated by Django 6.0.5 on 2026-06-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0013_produto_codigo_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoenvio',
            name='canal',
            field=models.CharField(default='whatsapp', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracaoenvio',
            name='marketplace',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='afiliado_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='frase_llm',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='produto',
            name='marketplace',
            field=models.CharField(db_index=True, default='mercadolivre', max_length=20),
        ),
    ]
