# Generated by Django 6.0.5 on 2026-06-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0014_configuracaoenvio_canal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupomcodigo',
            name='categorias',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
