# Generated by Django 6.0.5 on 2026-06-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0015_cupomcodigo_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoenvio',
            name='janela_fim',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='configuracaoenvio',
            name='janela_inicio',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='configuracaoenvio',
            name='proximo_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
