# Generated by Django 6.0.6 on 2026-06-14 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0017_produto_asin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoenvio',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicoenvio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LinkAfiliadoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_isca', models.URLField(blank=True, default='', max_length=1000)),
                ('link_afiliado', models.URLField(blank=True, default='', max_length=1000)),
                ('afiliado_ok', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_usuario', to='scrapers.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_afiliado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'produto')},
            },
        ),
    ]
