# Generated by Django 6.0.6 on 2026-07-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0020_produto_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(db_index=True, max_length=20)),
                ('chave', models.CharField(db_index=True, max_length=300)),
                ('preco', models.FloatField()),
                ('data', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['marketplace', 'chave', 'data'], name='scrapers_pr_marketp_ad5a0c_idx')],
            },
        ),
    ]
