# Generated by Django 6.0.6 on 2026-07-04 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0021_precohistorico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalMonitorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=120)),
                ('destino_canal', models.CharField(default='whatsapp', max_length=20)),
                ('destino_grupo_id', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_id', models.BigIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canais_monitorados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnvioCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(db_index=True, max_length=64)),
                ('data', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_canal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'chave')},
            },
        ),
    ]
