# Generated by Django 6.0.6 on 2026-07-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0022_canalmonitorado_enviocanal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='link_original',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='produto',
            name='link_produto',
            field=models.URLField(max_length=1000),
        ),
    ]
