# Generated by Django 6.0.6 on 2026-07-09 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0027_cupom_trust_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receitaafiliado',
            name='cliques',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receitaafiliado',
            name='conversoes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receitaafiliado',
            name='granularidade',
            field=models.CharField(default='dia', max_length=20),
        ),
        migrations.AddField(
            model_name='receitaafiliado',
            name='origem',
            field=models.CharField(default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='receitaafiliado',
            name='periodo_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receitaafiliado',
            name='periodo_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RelatorioSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('nunca', 'Nunca sincronizado'), ('rodando', 'Sincronizando'), ('ok', 'Sincronizado'), ('erro', 'Erro'), ('acao', 'Precisa de ação')], db_index=True, default='nunca', max_length=20)),
                ('ultimo_inicio', models.DateTimeField(blank=True, null=True)),
                ('ultimo_fim', models.DateTimeField(blank=True, null=True)),
                ('ultimo_sucesso', models.DateTimeField(blank=True, null=True)),
                ('proxima_execucao', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('erro', models.CharField(blank=True, default='', max_length=500)),
                ('registros_criados', models.PositiveIntegerField(default=0)),
                ('registros_atualizados', models.PositiveIntegerField(default=0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syncs_relatorio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'marketplace')},
            },
        ),
    ]
