# Generated by Django 6.0.6 on 2026-07-10 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0028_receitaafiliado_cliques_receitaafiliado_conversoes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='info', max_length=10)),
                ('pipeline', models.CharField(choices=[('onboarding', 'Onboarding'), ('scraper', 'Scraper'), ('ranking', 'Ranking'), ('publicacao', 'Publicação'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('relatorios', 'Relatórios'), ('redirect', 'Redirect'), ('sistema', 'Sistema')], db_index=True, max_length=30)),
                ('evento', models.CharField(db_index=True, max_length=80)),
                ('mensagem', models.CharField(max_length=500)),
                ('contexto', models.JSONField(blank=True, default=dict)),
                ('erro', models.TextField(blank=True, default='')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_operacionais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['pipeline', 'level', 'criado_em'], name='scrapers_ev_pipelin_0ef216_idx')],
            },
        ),
    ]
