# Generated by Django 6.0.7 on 2026-07-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0032_remove_legacy_produto_chave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventooperacional',
            name='pipeline',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('scraper', 'Scraper'), ('ranking', 'Ranking'), ('publicacao', 'Publicação'), ('conexao', 'Conexão'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('relatorios', 'Relatórios'), ('redirect', 'Redirect'), ('sistema', 'Sistema')], db_index=True, max_length=30),
        ),
    ]
