# Generated by Django 6.0.7 on 2026-07-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0033_alter_eventooperacional_pipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriosync',
            name='status',
            field=models.CharField(choices=[('nunca', 'Nunca sincronizado'), ('rodando', 'Sincronizando'), ('ok', 'Sincronizado'), ('erro', 'Erro'), ('acao', 'Precisa de ação'), ('nao_configurado', 'Sincronização automática indisponível')], db_index=True, default='nunca', max_length=20),
        ),
    ]
