# Generated by Django 6.0.7 on 2026-07-16 02:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0034_alter_relatoriosync_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupomnormalizado',
            name='ultima_observacao',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fonte',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ultima_observacao',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='publicacao',
            index=models.Index(fields=['usuario', 'criada_em'], name='scrapers_pu_usuario_ceb873_idx'),
        ),
        migrations.AddIndex(
            model_name='receitaafiliado',
            index=models.Index(fields=['usuario', 'marketplace', 'data'], name='scrapers_re_usuario_ce752e_idx'),
        ),
    ]
