# Generated by Codex on 2026-07-16
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("scrapers", "0035_alter_cupomnormalizado_ultima_observacao_and_more")]

    operations = [
        migrations.AlterField(
            model_name="publicacao",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"), ("enviado", "Enviado"),
                    ("falhou", "Falhou"), ("incerto", "Confirmação pendente"),
                    ("ignorado", "Ignorado"),
                ],
                db_index=True, default="pendente", max_length=20,
            ),
        ),
    ]
