# Generated by Codex on 2026-07-16
#
# ATENÇÃO — esta cópia da classificação está CONGELADA e já divergiu.
#
# As funções abaixo duplicam incidentes_saude.py de propósito: importar o módulo de
# produção numa migração puxa o modelo atual, com campos que só existem em migrações
# futuras (incidente_processado, da 0038), e o backfill quebra. A decisão está certa.
#
# O custo apareceu depois: incidentes_saude ganhou a regra
# "getchat"/"módulos internos" -> whatsapp_store_recarregado, e esta cópia não. Os
# eventos backfilled viraram publicacao_falhou enquanto os novos viram
# whatsapp_store_recarregado — DOIS incidentes para o mesmo problema, porque a chave
# inclui a causa. A 0042 consolida os que este arquivo classificou errado.
#
# Não sincronize as regras aqui: em banco existente esta migração não roda de novo, e
# em banco novo a tabela de eventos está vazia. Se precisar de uma nova classificação
# retroativa, escreva outra data migration.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hashlib


def _texto(evento):
    return " ".join([evento.evento or "", evento.mensagem or "", evento.erro or ""]).lower()


def _causa(evento):
    contexto = evento.contexto or {}
    if contexto.get("causa"):
        return str(contexto["causa"])[:80]
    texto = _texto(evento)
    if evento.evento == "send_failed":
        if "getstate timeout" in texto:
            return "whatsapp_preflight_timeout"
        if "detached frame" in texto or "recarregando" in texto:
            return "whatsapp_frame_recarregado"
        if "confirma" in texto or "ack" in texto:
            return "whatsapp_confirmacao"
        if "link de afiliado" in texto or "link builder" in texto:
            return "link_afiliado_recusado"
        if texto.strip().endswith(" r") or "\nr" in texto:
            return "whatsapp_erro_minificado"
        return "publicacao_falhou"
    if evento.evento == "send_timeout":
        return "whatsapp_timeout_entrega"
    return evento.evento


def _escopo(evento):
    contexto = evento.contexto or {}
    if evento.evento.startswith("send_") or evento.pipeline in {"whatsapp", "telegram"}:
        canal = contexto.get("canal") or ("whatsapp" if evento.pipeline == "whatsapp" else "")
        destino = contexto.get("destino") or contexto.get("grupo_id") or "destino desconhecido"
        return f"{canal}:{destino}"[:255]
    for campo in ("marketplace", "fonte", "servico", "config_id", "view"):
        if contexto.get(campo):
            return f"{campo}:{contexto[campo]}"[:255]
    return "sistema"


def _chave(evento, causa, escopo):
    bruto = f"{evento.pipeline}|{causa}|{evento.usuario_id or 0}|{escopo}".encode()
    return hashlib.sha256(bruto).hexdigest()


def backfill_incidentes(apps, schema_editor):
    # Migrações não podem importar modelos de produção: eles podem ter campos ou
    # classes de relacionamento diferentes dos disponíveis neste ponto do histórico.
    # Use somente o registro histórico fornecido pelo Django e IDs nas relações.
    EventoOperacional = apps.get_model("scrapers", "EventoOperacional")
    IncidenteSaude = apps.get_model("scrapers", "IncidenteSaude")

    for evento in EventoOperacional.objects.order_by("criado_em").iterator():
        escopo = _escopo(evento)
        if evento.evento == "send_ok":
            IncidenteSaude.objects.filter(
                status="aberto", usuario_id=evento.usuario_id, escopo=escopo,
                pipeline__in=("publicacao", "whatsapp", "telegram"),
            ).update(status="concluido", confirmado_em=evento.criado_em,
                     confirmacao="Envio real posterior concluído com sucesso.")
            continue
        if evento.evento == "sync_ok":
            IncidenteSaude.objects.filter(
                status="aberto", usuario_id=evento.usuario_id, pipeline="relatorios",
                escopo=escopo,
            ).update(status="concluido", confirmado_em=evento.criado_em,
                     confirmacao="Sincronização posterior concluída com sucesso.")
            continue
        if evento.evento == "conexao_voltou":
            IncidenteSaude.objects.filter(
                status="aberto", usuario_id=evento.usuario_id, pipeline="conexao",
                escopo=escopo,
            ).update(status="concluido", confirmado_em=evento.criado_em,
                     confirmacao="Conexão posterior restabelecida.")
            continue
        if evento.level not in {"warning", "error"}:
            continue

        causa = _causa(evento)
        incidente, criado = IncidenteSaude.objects.get_or_create(
            chave=_chave(evento, causa, escopo),
            defaults={
                "causa": causa, "pipeline": evento.pipeline, "escopo": escopo,
                "usuario_id": evento.usuario_id, "level": evento.level,
                "primeira_ocorrencia": evento.criado_em,
                "ultima_ocorrencia": evento.criado_em,
                "ultima_mensagem": evento.mensagem,
                "contexto": evento.contexto or {},
                "evento_origem_id": evento.id,
            },
        )
        if not criado:
            incidente.ocorrencias += 1
            incidente.ultima_ocorrencia = evento.criado_em
            incidente.ultima_mensagem = evento.mensagem
            incidente.contexto = evento.contexto or {}
            incidente.evento_origem_id = evento.id
            incidente.level = "error" if evento.level == "error" else incidente.level
            incidente.status = "aberto"
            incidente.confirmado_em = None
            incidente.confirmacao = ""
            incidente.save(update_fields=[
                "ocorrencias", "ultima_ocorrencia", "ultima_mensagem", "contexto",
                "evento_origem", "level", "status", "confirmado_em", "confirmacao",
            ])


class Migration(migrations.Migration):
    dependencies = [("scrapers", "0036_publicacao_status_incerto")]

    operations = [
        migrations.CreateModel(
            name="IncidenteSaude",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chave", models.CharField(max_length=64, unique=True)),
                ("causa", models.CharField(db_index=True, max_length=80)),
                ("pipeline", models.CharField(db_index=True, max_length=30)),
                ("escopo", models.CharField(db_index=True, default="sistema", max_length=255)),
                ("level", models.CharField(default="warning", max_length=10)),
                ("status", models.CharField(choices=[("aberto", "Aberto"), ("concluido", "Ajuste concluído")], db_index=True, default="aberto", max_length=12)),
                ("ocorrencias", models.PositiveIntegerField(default=1)),
                ("primeira_ocorrencia", models.DateTimeField(default=django.utils.timezone.now)),
                ("ultima_ocorrencia", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("ultima_mensagem", models.CharField(blank=True, default="", max_length=500)),
                ("contexto", models.JSONField(blank=True, default=dict)),
                ("confirmado_em", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("confirmacao", models.CharField(blank=True, default="", max_length=255)),
                ("evento_origem", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="incidentes", to="scrapers.eventooperacional")),
                ("usuario", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="incidentes_saude", to=settings.AUTH_USER_MODEL)),
            ],
            options={"indexes": [models.Index(fields=["status", "ultima_ocorrencia"], name="scrapers_in_status_e02206_idx")]},
        ),
        migrations.RunPython(backfill_incidentes, migrations.RunPython.noop),
    ]
