# Generated by Codex on 2026-07-16
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def backfill_incidentes(apps, schema_editor):
    # A tabela já existe neste ponto. Reaproveitar o classificador de produção
    # mantém o significado dos eventos antigos idêntico ao dos novos.
    from apps.scrapers.incidentes_saude import reconciliar_eventos
    # Use o modelo histórico: importar o modelo de produção nesta migração
    # incluiria campos adicionados em migrações futuras no SELECT.
    EventoOperacional = apps.get_model("scrapers", "EventoOperacional")
    reconciliar_eventos(EventoOperacional.objects.all())


class Migration(migrations.Migration):
    dependencies = [("scrapers", "0036_publicacao_status_incerto")]

    operations = [
        migrations.CreateModel(
            name="IncidenteSaude",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chave", models.CharField(max_length=64, unique=True)),
                ("causa", models.CharField(db_index=True, max_length=80)),
                ("pipeline", models.CharField(db_index=True, max_length=30)),
                ("escopo", models.CharField(db_index=True, default="sistema", max_length=255)),
                ("level", models.CharField(default="warning", max_length=10)),
                ("status", models.CharField(choices=[("aberto", "Aberto"), ("concluido", "Ajuste concluído")], db_index=True, default="aberto", max_length=12)),
                ("ocorrencias", models.PositiveIntegerField(default=1)),
                ("primeira_ocorrencia", models.DateTimeField(default=django.utils.timezone.now)),
                ("ultima_ocorrencia", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("ultima_mensagem", models.CharField(blank=True, default="", max_length=500)),
                ("contexto", models.JSONField(blank=True, default=dict)),
                ("confirmado_em", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("confirmacao", models.CharField(blank=True, default="", max_length=255)),
                ("evento_origem", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="incidentes", to="scrapers.eventooperacional")),
                ("usuario", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="incidentes_saude", to=settings.AUTH_USER_MODEL)),
            ],
            options={"indexes": [models.Index(fields=["status", "ultima_ocorrencia"], name="scrapers_in_status_e02206_idx")]},
        ),
        migrations.RunPython(backfill_incidentes, migrations.RunPython.noop),
    ]
