# Generated by Django 6.0.7 on 2026-07-17 13:14

from django.db import migrations, models


def marcar_prontos(apps, schema_editor):
    """Quem já tem link nasce 'pronto', não 'pendente'.

    O default do campo é 'pendente', e sem isto toda linha já resolvida voltaria
    para a fila do worker — que iria regerar do zero, no Link Builder, links que já
    existiam. Sem `usuario` no queryset de propósito: vale para todas as contas.
    """
    Link = apps.get_model("scrapers", "LinkAfiliadoUsuario")
    Link.objects.exclude(link_afiliado="").update(estado="pronto")


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0040_remove_default_affiliate_disclosure'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkafiliadousuario',
            name='estado',
            field=models.CharField(choices=[('pendente', 'Na fila'), ('pronto', 'Link gerado'), ('nao_afiliavel', 'Não afiliável'), ('erro', 'Falhou')], db_index=True, default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='linkafiliadousuario',
            name='proxima_tentativa',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='linkafiliadousuario',
            name='tentativas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='linkafiliadousuario',
            name='ultima_tentativa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkafiliadousuario',
            name='ultimo_erro',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.RunPython(marcar_prontos, migrations.RunPython.noop),
    ]
