# Generated by Django 6.0.6 on 2026-07-21 22:53

from django.db import migrations, models


def backfill_categoria(apps, schema_editor):
    """Preenche `categoria` dos cupons existentes a partir do `escopo` já
    normalizado nas regras (ver 0044). Sem isso o filtro por categoria só
    enxergaria cupons reingeridos após esta migração."""
    CupomNormalizado = apps.get_model("scrapers", "CupomNormalizado")
    for cupom in CupomNormalizado.objects.all().iterator(chunk_size=500):
        raw = cupom.regras if isinstance(cupom.regras, dict) else {}
        escopo = raw.get("escopo")
        categoria = ("" if escopo is None else str(escopo).strip())[:100]
        if categoria and categoria != cupom.categoria:
            cupom.categoria = categoria
            cupom.save(update_fields=["categoria"])


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0044_publicacao_cupom_e_regras_canonicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupomnormalizado',
            name='categoria',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.RunPython(backfill_categoria, migrations.RunPython.noop),
    ]
