# Generated by Django 6.0.7 on 2026-07-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0045_cupomnormalizado_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='relampago',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
