# Generated by Django 6.0.7 on 2026-07-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0049_produto_nome_llm'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkafiliadousuario',
            name='url_canonica',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='linkafiliadousuario',
            name='verificacao_motivo',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='linkafiliadousuario',
            name='verificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkafiliadousuario',
            name='verificado_ok',
            field=models.BooleanField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
