# Generated by Django 6.0.6 on 2026-07-26 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_organization_membership'),
        ('scrapers', '0050_linkafiliadousuario_url_canonica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canalmonitorado',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canais_monitorados', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='cliquepublicacao',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliques_publicacao', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='configuracaoenvio',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='cupomnormalizado',
            name='data_scope',
            field=models.CharField(choices=[('public', 'Público'), ('organization', 'Organização')], db_index=True, default='public', max_length=16),
        ),
        migrations.AddField(
            model_name='cupomnormalizado',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupons_normalizados', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='cupompreparacao',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupons_preparados', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='enviocanal',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios_canal', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='eventooperacional',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_operacionais', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='execucaoingestao',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execucoes_ingestao', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='historicoenvio',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='incidentesaude',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_saude', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='integracaoafiliado',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integracoes_afiliado', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='linkafiliadocupomusuario',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links_cupons', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='linkafiliadousuario',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links_afiliado', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_scope',
            field=models.CharField(choices=[('public', 'Público'), ('organization', 'Organização')], db_index=True, default='public', max_length=16),
        ),
        migrations.AddField(
            model_name='produto',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='produtocupom',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto_cupons', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='programaafiliado',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programas_afiliado', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='receitaafiliado',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receitas_afiliado', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='relatoriosync',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syncs_relatorio', to='accounts.organization'),
        ),
    ]
