# Generated by Django 6.0.7 on 2026-08-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    """Solta o teto de 255 caracteres da lista de sub-nichos de uma regra.

    Só alarga a coluna (varchar -> text), então não perde dado e não precisa de
    backfill. Não há índice nem unicidade sobre `termo_busca`.
    """

    dependencies = [
        ('scrapers', '0055_cupons_validados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoenvio',
            name='termo_busca',
            field=models.TextField(blank=True, default=''),
        ),
    ]
