# Generated by Django 6.0.7 on 2026-08-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0057_produto_nome_normalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoenvio',
            name='dias_semana',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracaoenvio',
            name='pausada_ate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracaoenvio',
            name='tipo',
            field=models.CharField(choices=[('ofertas', 'Ofertas e cupons com produto'), ('aviso_cupons', 'Aviso de cupons novos')], default='ofertas', max_length=20),
        ),
    ]
