# Generated by Django 6.0.7 on 2026-09-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0070_coupon_validation_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentesaude',
            name='alerta_tentado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentesaude',
            name='alertado_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
