# Generated by Django 6.0.7 on 2026-09-02 21:17
"""Fecha a identidade de `Produto` no schema.

A fusão em si roda pelo comando `fundir_produtos_duplicados`, porque é
destrutiva e precisa de `--dry-run` revisável antes. Mas os índices únicos
abaixo falham se sobrar UMA duplicata na hora do deploy — e entre a fusão
manual e este deploy os workers continuam gravando. Por isso a migração faz
uma varredura final de fusão antes de criar os índices: idempotente, não faz
nada quando o catálogo já está limpo, e evita um deploy abortado por uma
linha nascida no meio do caminho.
"""
import hashlib
import hmac

from django.conf import settings
from django.db import migrations, models


def _system_context(schema_editor):
    """Abre o contexto cross-tenant, como toda migração de dados deste app.

    Sem isto o RLS de produção esconde TODAS as linhas da conexão da migração,
    e a varredura percorre um conjunto vazio: a migração "roda com sucesso" sem
    fundir nada, e aí o índice único estoura na linha seguinte. Mesmo helper de
    `0064_purga_associacao_vitrine_generica`.
    """
    connection = schema_editor.connection
    if connection.vendor != "postgresql" or not settings.TENANT_CONTEXT_SIGNING_KEY:
        return
    assinatura = hmac.new(
        settings.TENANT_CONTEXT_SIGNING_KEY.encode("utf-8"), b"system:", hashlib.sha256,
    ).hexdigest()
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT set_config('app.system_context', 'on', true), "
            "set_config('app.system_signature', %s, true)",
            [assinatura],
        )


def fundir_remanescentes(apps, schema_editor):
    _system_context(schema_editor)
    # Import do módulo real (não do histórico de migração): a fusão precisa dos
    # managers e das regras de precedência de link, que o `apps.get_model`
    # histórico não carrega.
    from apps.scrapers import fusao_produtos

    # Fundir antes de canonicalizar: canonicalizar primeiro faria duas linhas
    # convergirem para o mesmo valor, e o índice único criado logo abaixo
    # transformaria esse UPDATE em IntegrityError.
    resumo = fusao_produtos.executar()
    fusao_produtos.canonicalizar_links()
    if resumo["produtos_apagados"]:
        print(f"  fusão final: {resumo['produtos_apagados']} produto(s) duplicado(s) removido(s)")


def nao_desfaz(apps, schema_editor):
    """Fusão não tem volta: o caminho de reversão é o snapshot do volume."""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_browsersession'),
        ('scrapers', '0071_incidente_alerta_dedup_no_banco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(fundir_remanescentes, nao_desfaz),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True), models.Q(('asin', ''), _negated=True)), fields=('marketplace', 'asin'), name='uniq_produto_publico_asin'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False), models.Q(('asin', ''), _negated=True)), fields=('marketplace', 'owner', 'asin'), name='uniq_produto_privado_asin'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True), ('asin', '')), fields=('marketplace', 'link_produto'), name='uniq_produto_publico_link'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False), ('asin', '')), fields=('marketplace', 'owner', 'link_produto'), name='uniq_produto_privado_link'),
        ),
    ]
