# Generated by Django 6.0.7 on 2026-09-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0072_produto_chave_natural'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoenvio',
            name='preco_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracaoenvio',
            name='preco_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracaoenvio',
            name='termos_negativos',
            field=models.TextField(blank=True, default=''),
        ),
    ]
