# Generated by Django 6.0.8 on 2026-09-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0075_gastoia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriosync',
            name='status',
            field=models.CharField(choices=[('nunca', 'Nunca sincronizado'), ('rodando', 'Sincronizando'), ('ok', 'Sincronizado'), ('erro', 'Erro'), ('acao', 'Precisa de ação'), ('ocupado', 'Recurso ocupado'), ('nao_configurado', 'Sincronização automática indisponível')], db_index=True, default='nunca', max_length=20),
        ),
    ]
