# Generated by Django 6.0.8 on 2026-09-21 17:34

import apps.accounts.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0076_relatoriosync_status_ocupado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta_id', models.CharField(blank=True, default='', max_length=32)),
                ('access_token', apps.accounts.fields.EncryptedCharField(blank=True, default='', max_length=1024)),
                ('refresh_token', apps.accounts.fields.EncryptedCharField(blank=True, default='', max_length=1024)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_erro', models.CharField(blank=True, default='', max_length=200)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
