# Generated by Django 6.0.8 on 2026-09-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0077_mlapitoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MLApiToken',
        ),
    ]
