macro_dict = {"Automotivo": ["VEHICLE", "MOTORCYCLE", "BICYCLE", "AUTOMOTIVE", "COMBUSTION", "CYCLING", "GPS", "BEARING", "CARS", "ENGINE", "MOTOR", "PEDAL", "TRUCK", "AMBULANCE", "BICYCLES", "CAR", "DRIVING", "GREASE", "MOTORCYCLES", "MOTORCYCLIST", "PARKING", "RADIAL", "REVERSE", "SPARK", "SUSPENSION", "TIRE", "TRANSPORT", "TRUCKS", "WAGONS", "WHEEL"],
"Náutica, Praia e Surf": ["NAUTICAL", "SURFBOARD", "BEACH", "SUN", "BODYBOARDS", "KAYAKS", "OUTBOARD", "PADDLE", "SUNBATHING", "SURFBOARDS", "WETSUITS"],
"Casa, Móveis e Decoração": ["DECORATIVE", "HOME", "TABLE", "FURNITURE", "BED", "CANDLE", "DINING", "FOLDING", "CARPET", "CURTAIN", "HOUSEHOLD", "INDOOR", "LAMP", "MIRROR", "SLEEPING", "STORAGE", "AMBIENT", "BEDDING", "BEDROOM", "BEDS", "BLANKETS", "BOOKCASES", "BOOKENDS", "CABINETS", "CANDELABRAS", "CANDLES", "CHAIR", "CLOCKS", "COASTERS", "COMFORTERS", "COMFORTER", "CORK", "CUSHIONS", "CUSHION", "DESIGN", "DESK", "DRAWERS", "ENTRYWAY", "FRAME", "HAMMOCKS", "HANGING", "HEADBOARDS", "HOUSE", "LIVING", "LOCKERS", "MAILBOXES", "MATTRESSES", "MATTRESS", "MIRRORS", "MOULDINGS", "NIGHTSTANDS", "PICTURE", "PILLOWS", "PLACEMATS", "POSTERS", "POUFS", "QUILTS", "SHADE", "SHELVES", "SIDEBOARDS", "SOFAS", "SOFA", "STOOLS", "TABLECLOTHS", "TOWEL", "UNDERPLATES", "WALLPAPER", "WARDROBES"],
"Casa e Construção": ["WATER", "BATHROOM", "CONSTRUCTION", "DOOR", "TOILET", "PAINT", "FLOOR", "SHOWER", "GAS", "WALL", "BATH", "HOSE", "CONCRETE", "PIPE", "ROOF", "TILE", "WOOD", "DRAIN", "FENCE", "GATE", "MASONRY", "SLATWALL", "ASPHALT", "BARBED", "BASEBOARDS", "BATHTUBS", "BLOCK", "BRICKS", "CAULK", "CEMENT", "CERAMIC", "COUNTERTOPS", "DOORBELLS", "DOORS", "DRYWALLS", "EXPANDING", "FLOORS", "GARAGE", "LEAK", "LOCKING", "LOCK", "MODULAR", "PADLOCKS", "PATIO", "PEGBOARDS", "PERGOLAS", "PIPES", "PLUNGERS", "PLUNGE", "RISER", "SCAFFOLDS", "SEALANTS", "SHUT", "SINK", "STAIN", "TAP", "TEXTURED", "TEXTURE", "TOILETS", "URINALS", "VARNISHES", "WATERPROOFING", "WATERPROOF", "WINDOWS"],
"Ferramentas e Manutenção": ["MANUAL", "HAND", "TOOL", "CUTTING", "DRILL", "HARD", "PNEUMATIC", "LASER", "WELDING", "3D", "WORK", "MULTIPURPOSE", "CHAINSAW", "CNC", "EDGE", "MEASURING", "MECHANICAL", "MECHANIC", "MITER", "ANGLE", "AXES", "BOLT", "BORESCOPES", "CALIPERS", "CENTRIFUGAL", "CHISELS", "CLAMPS", "CLAMP", "CRIMPING", "DIAL", "DIE", "HAMMER", "HARDWARE", "HOLE", "HOOK", "JIG", "LADDERS", "LINEMAN", "LOAD", "MACHINE", "MICROMETERS", "MILLING", "OSCILLATING", "PINCERS", "PLIER", "POWERED", "PRECISION", "PUNCHING", "RIVETS", "RIVET", "SANDBLASTERS", "SANDER", "SANDPAPERS", "SCISSORS", "SCREWS", "SCREW", "SHARPENING", "SLEDGEHAMMERS", "SOLDERING", "SUBMERSIBLE", "SUCTION", "TAMPING", "TOOLS", "TORQUE", "TURNBUCKLES", "UTILITY", "VIBRATION", "VISES", "WRENCHES"],
"Jardim, Piscina e Área Externa": ["POOL", "GARDEN", "GARDENING", "INFLATABLE", "IRRIGATION", "HYDROPONIC", "INSECT", "LAWN", "PLANT", "FLOATING", "FOG", "GERMINATION", "GRASS", "GREEN", "HEDGE", "HOES", "INSECTICIDES", "MOSQUITO", "MOSSES", "OUTDOOR", "PLANTING", "PLANTS", "PRUNING", "REPELLENT", "SPRINKLES", "TILLERS", "WATERING", "WHEELBARROWS"],
"Eletrodomésticos": ["REFRIGERATOR", "MICROWAVE", "BLENDER", "REFRIGERATORS", "STOVETOP", "APPLIANCE", "BLENDERS", "COOKTOPS", "DISHWASHERS", "DISHWASHING", "DISTILLERS", "DRYER", "FREEZERS", "FREEZER", "FRYING", "IMMERSION", "IRONS", "MICROWAVES", "MIXERS", "OVENS", "OVEN", "RANGES", "TOASTERS"],
"Limpeza e Lavanderia": ["WASHING", "VACUUM", "CLEANING", "LAUNDRY", "BROOM", "HYGIENIC", "WASTE", "BACKWASH", "BLEACHES", "BROOMS", "BUCKETS", "CLOTHESPINS", "DEBRIS", "DOMESTIC", "DRYING", "DRY", "DUSTERS", "DUSTPANS", "IRONING", "SANITARY", "SOAP", "SQUEEGEES", "TRASH", "WET"],
"Climatização e Aquecimento": ["AIR", "THERMAL", "COLD", "HOT", "FAN", "FANS", "HEATING", "HEAT", "REFRIGERANT", "REFRIGERATED", "VENTILATION"],
"Eletrônicos e Informática": ["LAPTOP", "DIGITAL", "PRINTER", "COMPUTER", "PORTABLE", "ELECTRONIC", "NETWORK", "DESKTOP", "PROJECTOR", "TABLET", "KEYBOARD", "MEMORY", "SMART", "WIRELESS", "ANALOG", "EXTERNAL", "MICRO", "NOTEBOOKS", "PC", "PDA", "PLASMA", "SCREEN", "USB", "ANTIVIRUS", "AUXILIARY", "CALCULATORS", "CODING", "CPU", "DATA", "DEVICE", "DISPLAY", "EMBEDDED", "FLOPPY", "GATEWAYS", "GRAPHICS", "IP", "LCD", "MODEMS", "MONITOR", "MOUSE", "PENDRIVES", "PHOTOCOPIER", "PRINTERS", "PROJECTORS", "RAM", "ROUTERS", "SAT", "SCANNERS", "SERVER", "STYLUSES", "TABLETS", "TAB", "TELEPROMPTERS", "UPS", "VR", "WEBCAMS"],
"Celulares, Telefonia e Wearables": ["CELLPHONE", "SMARTWATCH", "SIM", "TELEPHONE", "TELEPHONY", "CELLPHONES", "CELL", "MOBILE", "SMARTWATCHES", "TELEPHONES", "WALKIE"],
"Áudio, Vídeo e Fotografia": ["CAMERA", "TV", "VIDEO", "AUDIO", "PHOTOGRAPHIC", "DJ", "DRONE", "REMOTE", "SOUND", "DRONES", "HEADPHONE", "PHOTO", "SPEAKERS", "STREAMING", "AM", "AV", "BOOMBOXES", "EQUALIZERS", "FLASH", "HEADPHONES", "HEADSET", "MICROPHONES", "MICROPHONE", "MONOCULARS", "MONOPODS", "PHOTOGRAPHS", "PHOTOGRAPHY", "PREAMPLIFIERS", "RADIO", "RECEIVERS", "SPEAKER", "TELESCOPES", "TELEVISIONS", "TURNTABLES", "TURNTABLE"],
"Materiais Elétricos e Componentes": ["ELECTRIC", "MAGNETIC", "ELECTRICAL", "FIBER", "LIGHT", "CABLE", "LED", "POWER", "SOLAR", "VOLTAGE", "BUTTON", "ELECTRODE", "WIRE", "BATTERY", "BEAM", "CIRCUIT", "CONDUCTIVE", "CONDUCTIVITY", "DC", "DIMMERS", "DIRECT", "ELECTRICITY", "ELECTROLYTIC", "ENERGY", "FLOOD", "IGBT", "INDUCTIVE", "INFRARED", "INTEGRATED", "MICROCONTROLLERS", "MICROCONTROLLER", "MULTIMETERS", "PHOTOCONTROLS", "PLUG", "POE", "POINTS", "POTENTIOMETERS", "PROTOBOARDS", "PUSH", "RECTIFIER", "RESISTANCE", "RESISTORS", "STABILIZERS", "THERMISTORS", "TIMERS", "TRANSISTORS", "VARIABLE", "VOLTMETERS"],
"Games, Brinquedos e Hobbies": ["TOY", "MODEL", "DOLL", "GAME", "ACTION", "BOARD", "BUBBLE", "DICE", "MODELING", "RC", "SCALEXTRIC", "STUFFED", "ARCADE", "AUTOMODELISM", "CARDS", "DARTS", "DIECAST", "DOLLHOUSES", "DOLLHOUSE", "DOLLS", "FIDGET", "GAMEPADS", "JOKE", "JUGGLING", "MAGIC", "MINIATURES", "PLAYGROUND", "PLAYING", "POKER", "PUPPETS", "PUZZLES", "PUZZLE", "ROBOT", "ROULETTE", "SLIME", "SQUISHIES", "TOYS", "TRADING", "YO"],
"Bebês e Maternidade": ["BABY", "KIDS", "DIAPER", "INFANTS", "BABIES", "BREASTFEEDING", "KID", "NURSING", "PREGNANCY"],
"Pets e Animais": ["PET", "AQUARIUM", "CAT", "HORSE", "DOG", "BIRD", "ANIMAL", "BEEKEEPING", "RODENT", "REPTILE", "AGILITY", "AQUARIUMS", "BIRDHOUSES", "CATS", "DROPPING", "EQUINE", "FISHES", "FISH", "RABBIT", "RIDING", "TREAT"],
"Alimentos e Bebidas": ["FOOD", "CAKE", "ICE", "MEAT", "BREAD", "COCKTAIL", "COFFEE", "DRINKING", "DRINK", "EDIBLE", "EGG", "INSTANT", "MATE", "MILK", "PASTRY", "TEA", "WINE", "APPETIZER", "BUTTER", "CANDY", "CEREAL", "COOKIES", "HONEY", "LIQUOR", "NATURAL", "PASTA", "POPCORN", "POTATO", "READY", "SALT", "SALTY", "SPARKLING", "SUGAR", "SUSHI", "APERITIFS", "AREPAS", "BAKERY", "BAKING", "BALSAMIC", "BARBECUE", "BATTER", "BEANS", "BEERS", "BEER", "BEVERAGE", "BREADS", "BREAKFAST", "BROTHS", "CACAO", "CACHACAS", "CAKES", "CANDIES", "CANNED", "CEREALS", "CHINESE", "CHOCOLATES", "CHURRO", "CONDENSED", "CORN", "COUSCOUS", "CULINARY", "CUPCAKES", "DIPS", "DOUGH", "DRIED", "DULCE", "EGGS", "ENERGETIC", "FLAVORED", "FLOUR", "FONDUE", "FOODS", "FRUITS", "FRUIT", "GINGER", "GINGERBREADS", "GINS", "GLAZED", "GRANOLA", "GRATED", "GROCERY", "GROUND", "HAMBURGER", "HAZELNUT", "HERB", "ICED", "JAMS", "JUICES", "LENTILS", "LIQUORS", "MEATS", "MINERAL", "OATMEAL", "OMELETTE", "PANETTONES", "PASTAS", "PASTEL", "PEANUTS", "PEANUT", "QUINOAS", "RICE", "ROASTING", "SAKES", "SALAD", "SAUCES", "SAUSAGE", "SEASONINGS", "SHAWARMA", "SNACKS", "SPICES", "SPICE", "SWEETENERS", "SWEET", "VEGETABLES", "VEGETABLE", "VINEGARS", "VODKAS", "WHIPPED", "WHISKEYS", "WINES", "YERBA"],
"Cozinha, Mesa e Bar": ["KITCHEN", "COOKING", "RANGE", "BAR", "DISHES", "FLATWARE", "ROLLING", "CHALICES", "CHOPSTICKS", "CHOP", "COLANDERS", "CORKSCREWS", "CREAMERS", "CUP", "GRILL", "LADLES", "LUNCHBOXES", "MUDDLERS", "MUGS", "NAPKIN", "RAMEKINS", "SERVING", "SHAKER", "SQUEEZE", "STRAWS", "TABLETOP", "TABLEWARE", "TEAPOTS", "THERMOSES", "THERMO", "TOOTHPICK", "TRIVETS"],
"Beleza e Cuidados Pessoais": ["HAIR", "NAIL", "MAKEUP", "MANICURE", "HAIRDRESSING", "TATTOO", "EYEBROW", "FACIAL", "MASSAGE", "SKIN", "BEAUTY", "BRUSH", "DEPILATORY", "EYELASH", "LIP", "RADIOFREQUENCY", "SALON", "SELF", "BEARD", "BODY", "CUTICLE", "ESTHETIC", "FALSE", "RAZOR", "SHAVING", "STRAIGHT", "AFTERSHAVES", "AFTER", "BLACKHEAD", "BLUSHES", "CONCEALERS", "COSMETIC", "DEODORANTS", "EPILATORS", "ESSENTIAL", "EXFOLIATING", "EYELINERS", "EYESHADOWS", "FACE", "FAKE", "FOUNDATIONS", "GEL", "INGROWN", "INTIMATE", "LICE", "LIPSTICKS", "MASCARAS", "MICRONEEDLE", "NAILS", "PERFUMES", "PERMANENT", "PERSONAL", "PRESSOTHERAPY", "SHAPER", "STYLING", "SUNSCREENS", "TALCUMS", "TANNING", "TEMPORARY", "TOILETRY", "TWEEZERS", "VACUTHERAPY", "WRINKLE"],
"Saúde, Ortopedia e Equipamentos Médicos": ["DENTAL", "ORTHOPEDIC", "MEDICAL", "WHEELCHAIR", "BLOOD", "BREAST", "COMPRESSION", "HEARING", "NASAL", "PATIENT", "TEETH", "ACUPUNCTURE", "ANTIBACTERIAL", "ARM", "BACK", "BALANCE", "BUNION", "CATHETERS", "CERVICAL", "COLOSTOMY", "CONDOMS", "CORRECTION", "CORRECTIVE", "CRUTCHES", "ELBOW", "ERGONOMIC", "FINGER", "FIRST", "GAUZES", "HEALTH", "HEART", "HEMOSTATS", "HIP", "HUMAN", "HYDROPHILIC", "INCONTINENCE", "INFUSION", "INHALER", "INTERDENTAL", "KINESIOLOGY", "LEG", "LUMBAR", "MAGNIFYING", "MENSTRUAL", "MOUTHWASHES", "MOUTH", "NEBULIZERS", "NECK", "OPERATING", "ORAL", "ORTHODONTIC", "ORTHOPEDICS", "ORTHOTIC", "OTOSCOPES", "OXIMETERS", "OXYGEN", "PATCH", "PHYSICAL", "PILL", "PROTECTION", "SPLINTS", "STETHOSCOPES", "SUPPLEMENTS", "SURGICAL", "SYRINGES", "THERMOMETERS", "TONGUE", "TOOTHBRUSHES", "TOOTHBRUSH", "TOOTHPASTES", "TOOTHPASTE", "WHEELCHAIRS"],
"Moda, Calçados e Acessórios": ["CLOTHING", "SHOE", "CLOTHES", "FOOTWEAR", "COSPLAY", "COSTUME", "FASHION", "GLASSES", "NEOPRENE", "SPORTSWEAR", "TEXTILE", "TIE", "ADULT", "BABYDOLLS", "BELTS", "BLOUSES", "BODYSUITS", "BOOTS", "BRAS", "BRA", "COAT", "CORSETS", "COSTUMES", "DRESSES", "ESPADRILLES", "FANNY", "FEMALE", "FLATS", "FLIP", "GLOVES", "HATS", "HEADPIECES", "HEELS", "HEEL", "JACKETS", "JUMPSUITS", "LEGGINGS", "LINGERIE", "LOAFERS", "NECKTIES", "NIGHTGOWNS", "PAJAMAS", "PANTIES", "PANTS", "PANTYHOSE", "PONCHOS", "ROBES", "SANDALS", "SARONGS", "SCARVES", "SHIRTS", "SHOELACES", "SHORTS", "SKIRTS", "SLIPPERS", "SNAP", "SNEAKERS", "SNOWWEAR", "SOCKS", "SUITS", "SUNGLASSES", "SUSPENDERS", "SWEATERS", "SWEATSHIRTS", "SWIMWEAR", "SWIM", "TURBANS", "TURBAN", "TUTUS", "T", "UMBRELLAS", "UMBRELLA", "UNDERPANTS", "VEILS", "VESTS", "ZIPPERS"],
"Bolsas, Malas e Viagem": ["TRAVEL", "HANDBAG", "LUGGAGE", "BACKPACKS", "BAG", "BRIEFCASES", "HANDBAGS", "KEYCHAINS", "KEY", "LANYARDS", "POCKET", "SUITCASES", "SUITCASE", "TROLLEY", "WALLETS"],
"Joias, Relógios e Bijuterias": ["JEWELRY", "WATCH", "BRACELETS", "BROOCHES", "CHARMS", "CUFFLINKS", "DIAMOND", "EARRINGS", "NECKLACES", "PIERCINGS", "PRECIOUS", "RINGS", "WRISTWATCHES", "WRISTWATCH"],
"Esportes e Fitness": ["SPORT", "FOOTBALL", "BILLIARD", "SWIMMING", "MARTIAL", "TENNIS", "GYM", "BASKETBALL", "DANCE", "ROLLER", "SKATEBOARD", "AMERICAN", "BASEBALL", "PILATES", "SPORTS", "BARBELL", "EXERCISE", "SKI", "TRAINING", "VOLLEYBALL", "ABDOMINAL", "AB", "AEROBICS", "AEROBIC", "ANKLE", "BALL", "BODYWEIGHT", "CUE", "CURLING", "DUMBBELLS", "ELLIPTICALS", "FOOSBALL", "GOAL", "GRIPS", "GYMNASTIC", "HANDBALL", "JUMP", "KETTLEBELLS", "KICK", "LONGBOARDS", "MAT", "PERFORMANCE", "PICKLEBALL", "POUND", "REFEREE", "ROWING", "SHIN", "SPINNING", "STEPPERS", "TRAMPOLINES", "TRAMPOLINE", "TREADMILLS", "TREADMILL", "WEIGHT", "WORKOUT"],
"Camping, Pesca e Outdoor": ["FISHING", "CAMPING", "CLIMBING", "CANTEENS", "FISHER", "FLASHLIGHTS", "HIKING", "HYDRATION", "LIFE", "TENTS", "TENT", "TREKKING", "WADERS"],
"Armas, Tático e Defesa": ["TACTICAL", "GUN", "AIRSOFT", "ARCHERY", "PAINTBALL", "AIRGUN", "BUTTSTOCKS", "CROSSBOWS", "HUNTING", "KATANA", "KNIFE", "MACHETES", "MILITARY", "NUNCHAKUS", "PAINTBALLS", "QUIVERS", "SHOOTING", "SLINGSHOTS"],
"Papelaria, Escritório e Escola": ["SCHOOL", "OFFICE", "LABEL", "PAPER", "CARD", "TONER", "BILL", "BINDING", "CONTINUOUS", "DRAFTING", "FOLDER", "STATIONARY", "TAPE", "ADRESS", "BADGE", "BROCHURES", "BROCHURE", "CALENDARS", "CATALOGS", "CHALKBOARDS", "CHALKBOARD", "CHALKS", "DOCUMENT", "EDUCATIONAL", "ERASERS", "FILE", "FILING", "FOLDERS", "GEOMETRY", "INKWELLS", "INK", "LAMINATING", "LAMINATORS", "LEARNING", "LECTERNS", "MARKERS", "MARKING", "PENCILS", "PENCIL", "PENS", "PEN", "PLANNERS", "PRESENTATION", "STAMP", "STAPLER", "STICKERS", "STICKER", "STICKY", "TAG", "TONERS", "TRANSPARENCY", "WHITE"],
"Livros, Mídia e Conteúdo": ["BOOKS", "CD", "AUTHOR", "BOOKMARKS", "DISC", "EBOOKS", "MAGAZINES", "MAGAZINE", "POP", "READING", "WORLD"],
"Música e Instrumentos": ["MUSICAL", "STRING", "DRUM", "PERCUSSION", "MUSIC", "ACOUSTIC", "EFFECTS", "GUITAR", "INSTRUMENT", "ACCORDIONS", "AGOGOS", "BASS", "BONGOS", "CASTANETS", "CAVAQUINHOS", "CLARINETS", "CLASSICAL", "CYMBALS", "DRUMHEADS", "DRUMS", "DRUMSTICKS", "EFFECT", "FLUTES", "GUIROS", "HARMONICAS", "HORN", "JUKEBOXES", "MANDOLINS", "MEGAPHONES", "MELODICAS", "MIDI", "OCARINAS", "PEDALBOARDS", "PEDALBOARD", "PIANO", "PICKGUARDS", "REED", "SAXOPHONES", "SINGING", "SNARE", "STAGE", "STUDIO", "TAMBORIMS", "TAMBOURINES", "TIMBALES", "TROMBONES", "TRUMPET", "UKULELES", "VIDEOKE", "VIOLINS", "XYLOPHONES"],
"Arte, Artesanato e Costura": ["HABERDASHERY", "SEWING", "ARTISTIC", "FABRIC", "COTTON", "EMBROIDERY", "ARTIFICIAL", "CRAFT", "AIRBRUSHES", "ANILINE", "ARTS", "CANVAS", "CLAY", "COLOR", "DRAWING", "EASELS", "FABRICS", "GLUES", "HANDLOOMS", "KNITTING", "PAINTS", "RESINS", "RESIN", "SCULPTURED", "SCULPTURES", "SEQUINS", "STENCIL", "STONE", "TRANSFER", "WATERCOLORS", "YARNS"],
"Festas, Eventos e Presentes": ["PARTY", "CHRISTMAS", "CONFETTI", "GIFT", "BALLOONS", "BALLOON", "BIRTHDAY", "EASTER", "FLAGS", "MEDALS", "MEDAL", "MERRY", "NATIVITY", "PARTIES", "PLAGUES", "SOUVENIRS", "SOUVENIR", "TICKET", "TIKI", "TROPHIES", "WEDDING"],
"Colecionáveis e Antiguidades": ["COLLECTIBLE", "ANTIQUE", "ANTIQUES", "COINS", "COLLECTION", "COUNTERFEIT", "GRAMOPHONES", "TYPEWRITERS"],
"Embalagens e Descartáveis": ["DISPOSABLE", "PACKAGING", "BOX", "PLASTIC", "REUSABLE", "AIRTIGHT", "BLANK", "CAN", "CONTAINER", "CORRUGATED", "DESICCANT", "PALLETS", "PORTION", "SACHET", "SHRINK", "STACKABLE"],
"Comércio, Varejo e Serviços": ["COMMERCIAL", "SHOPPING", "CASH", "RECEPTION", "RETAIL", "BUSINESS", "CART", "CHECKOUT", "CHECK", "EMPLOYEE", "EXHIBITOR", "GONDOLA", "INCENTIVE", "MANNEQUINS", "MONEY", "PRICE", "PROMOTIONAL", "QUEUE", "SCHEDULED", "SERVICE", "STORE"],
"Segurança e Vigilância": ["SAFETY", "PROXIMITY", "EMERGENCY", "IDENTIFICATION", "PROTECTIVE", "RFID", "SURVEILLANCE", "ALARM", "CRIMINALISTIC", "FINGERPRINT", "FIRE", "REFLECTIVE", "SAFES", "SECURITY"],
"Indústria, Agro e Laboratório": ["INDUSTRIAL", "HYDRAULIC", "AGRICULTURAL", "BEAKERS", "CHEMICAL", "FARM", "GRADUATED", "HYGROMETERS", "LABORATORY", "MANIFOLD", "NEWTONS", "PH", "SILAGE", "SODIUM", "VOLUMETRIC"],
"Religião, Esoterismo e Espiritualidade": ["ESOTERIC", "ALTERNATIVE", "DREAMCATCHERS", "INCENSES", "INCENSE", "RUNES", "TAROT"],
"Tabacaria": ["CIGARETTE", "ASHTRAYS", "HOOKAHS", "HOOKAH", "LIGHTERS", "TOBACCO"],
"Materiais e Insumos": ["FIREWOOD", "OIL", "RUBBER", "METAL", "VINYL", "ADHESIVE", "ALUMINUM", "ANTI", "BRASS", "CARBON", "CHARCOAL", "FOAM", "GALVANIZED", "GLASS", "LATEX", "LIQUIDS", "LIQUID", "POLYCARBONATE", "POLYWIRE", "POLY", "SHEET", "SOLID", "SPRAY", "STEEL", "SYNTHETIC", "TUBE"],
"Outros": ["OTHER", "NON", "MINI", "ALL", "INDIVIDUAL", "BASIC", "COMBINED", "COMPLETE", "CONVENTIONAL", "DEEP", "DOUBLE", "DRAGGING", "E", "FULL", "LONG", "MULTI", "OBJECT", "QUICK", "REPLACEMENT", "SOFT", "UNCLASSIFIED", "UNIVERSAL"]}


# Monta índice reverso: prefixo → macro_categoria
prefixo_para_macro = {}
for macro, prefixos in macro_dict.items():
    for p in prefixos:
        prefixo_para_macro[p] = macro


def popular_macro_categorias():
    """
    Popula Produto.macro_categoria a partir de Produto.categoria (domain_id) usando
    o mapa de palavras-chave macro_dict. Reutilizável: chamada no fim do scrape e
    como ação avulsa. Exige Django configurado.
    """
    from apps.scrapers.models import Produto

    produtos_qs = (
        Produto.objects
        .exclude(categoria__isnull=True).exclude(categoria="").exclude(categoria="DESCONHECIDO")
    )
    atualizados = 0
    em_lote = []
    for produto in produtos_qs.iterator(chunk_size=500):
        prefixo = produto.categoria.split("_")[0]
        macro = prefixo_para_macro.get(prefixo)
        if produto.macro_categoria != macro:
            produto.macro_categoria = macro
            em_lote.append(produto)
        if len(em_lote) >= 500:
            Produto.objects.bulk_update(em_lote, ["macro_categoria"])
            atualizados += len(em_lote)
            em_lote = []
    if em_lote:
        Produto.objects.bulk_update(em_lote, ["macro_categoria"])
        atualizados += len(em_lote)

    print(f"Macro-categorias populadas: {atualizados} produtos atualizados.")
    return atualizados


if __name__ == "__main__":
    import os
    import django
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "core.settings")
    django.setup()
    popular_macro_categorias()
