# Generated by Django 6.0.6 on 2026-06-14 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verificado', models.BooleanField(default=False)),
                ('verificado_em', models.DateTimeField(blank=True, null=True)),
                ('afiliado_tag_ml', models.CharField(blank=True, default='', max_length=120)),
                ('afiliado_tag_amazon', models.CharField(blank=True, default='', max_length=120)),
                ('wa_session', models.CharField(blank=True, default='', max_length=64)),
                ('wa_estado', models.BooleanField(blank=True, null=True)),
                ('ml_estado', models.BooleanField(blank=True, null=True)),
                ('alerta_wa_em', models.DateTimeField(blank=True, null=True)),
                ('alerta_ml_em', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
