# Generated by Django 6.0.6 on 2026-06-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='amazon_creators_host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='perfil',
            name='amazon_credential_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='perfil',
            name='amazon_credential_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
