# Generated by Django 6.0.6 on 2026-07-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_perfil_amazon_creators_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
