# Generated by Django 6.0.6 on 2026-07-04 14:44

import apps.accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_perfil_amazon_creators_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='amazon_credential_secret',
            field=apps.accounts.fields.EncryptedCharField(blank=True, default='', max_length=512),
        ),
    ]
