# Generated by Django 6.0.6 on 2026-07-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_perfil_amazon_credential_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='amazon_elegivel',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='amazon_ultimo_erro',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
