# Generated by Django 6.0.6 on 2026-07-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_perfil_telegram_bot_token'),
        ('accounts', '0005_perfil_suspensao_cotas'),
    ]

    operations = [
    ]
