# Generated by Django 6.0.6 on 2026-07-09 17:20

import apps.accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_perfil_branding_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='telegram_bot_token',
            field=apps.accounts.fields.EncryptedCharField(blank=True, default='', max_length=512),
        ),
    ]
