# Generated by Django 6.0.6 on 2026-07-26 16:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_backfill_personal_organizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoLivreSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connection_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cipher_version', models.CharField(default='aes-256-gcm-v1', max_length=24)),
                ('key_version', models.CharField(max_length=32)),
                ('wrapped_dek', models.BinaryField()),
                ('wrap_nonce', models.BinaryField()),
                ('data_nonce', models.BinaryField()),
                ('ciphertext', models.BinaryField()),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('expired', 'Expirada'), ('decrypt_error', 'Erro de criptografia'), ('rotation_required', 'Rotação necessária')], db_index=True, default='active', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mercadolivre_session', to='accounts.organization')),
            ],
        ),
    ]
