# Generated by Django 6.0.6 on 2026-07-26 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_mercadolivresession'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(db_index=True, default='inactive', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_connection', to='accounts.organization')),
            ],
        ),
    ]
