# Generated by Django 6.0.7 on 2026-07-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_perfil_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadolivresession',
            name='last_probe_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mercadolivresession',
            name='last_probe_result',
            field=models.CharField(blank=True, choices=[('conectado', 'Conectado'), ('suspeito', 'Suspeito'), ('inconclusivo', 'Inconclusivo')], max_length=16),
        ),
        migrations.AddField(
            model_name='mercadolivresession',
            name='probe_failures',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mercadolivresession',
            name='probe_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mercadolivresession',
            name='status',
            field=models.CharField(choices=[('active', 'Ativa'), ('suspect', 'Suspeita'), ('expired', 'Expirada'), ('decrypt_error', 'Erro de criptografia'), ('rotation_required', 'Rotação necessária')], db_index=True, default='active', max_length=24),
        ),
    ]
