# Generated by Django 6.0.6 on 2026-07-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_perfil_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='fonte_catalogo_ml',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
