# Generated by Django 6.0.7 on 2026-08-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_perfil_active_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='pode_ligar_envio',
            field=models.BooleanField(default=False),
        ),
    ]
